"""baseline schema

Revision ID: 45bb59d3ebf6
Revises: 
Create Date: 2026-08-29 14:45:04.584995+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  - needed when a migration has a Vector column
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '45bb59d3ebf6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('identifier', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=False)
    op.create_table('studios',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('brand_color', sa.String(length=9), nullable=True),
    sa.Column('brand_logo_key', sa.Text(), nullable=True),
    sa.Column('default_face_retention_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studios_slug'), 'studios', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_webhook_external')
    )
    op.create_index(op.f('ix_webhook_events_external_id'), 'webhook_events', ['external_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qr_token', sa.String(length=32), nullable=False),
    sa.Column('tier_code', sa.String(length=16), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('branding_mode', sa.String(length=16), nullable=False),
    sa.Column('photo_retention_days', sa.Integer(), nullable=False),
    sa.Column('face_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('faces_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photos_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_qr_token'), 'events', ['qr_token'], unique=True)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index('ix_events_studio_created', 'events', ['studio_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_studio_id'), 'events', ['studio_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_studio_id'), 'users', ['studio_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_studio_id'), 'audit_log', ['studio_id'], unique=False)
    op.create_table('guest_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_face_retention_days', sa.Integer(), nullable=False),
    sa.Column('selfie_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_sessions_event_id'), 'guest_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_guest_sessions_studio_id'), 'guest_sessions', ['studio_id'], unique=False)
    op.create_index(op.f('ix_guest_sessions_token_hash'), 'guest_sessions', ['token_hash'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tier_code', sa.String(length=16), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_event_id'), 'payments', ['event_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_studio_id'), 'payments', ['studio_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('thumb_key', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photos_event_created', 'photos', ['event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_photos_event_id'), 'photos', ['event_id'], unique=False)
    op.create_index(op.f('ix_photos_status'), 'photos', ['status'], unique=False)
    op.create_index(op.f('ix_photos_studio_id'), 'photos', ['studio_id'], unique=False)
    op.create_index(op.f('ix_photos_uploaded_by'), 'photos', ['uploaded_by'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('family_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('faces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('photo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=False),
    sa.Column('bbox_x', sa.Integer(), nullable=False),
    sa.Column('bbox_y', sa.Integer(), nullable=False),
    sa.Column('bbox_w', sa.Integer(), nullable=False),
    sa.Column('bbox_h', sa.Integer(), nullable=False),
    sa.Column('det_score', sa.Float(), nullable=False),
    sa.Column('blur_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faces_event_id'), 'faces', ['event_id'], unique=False)
    op.create_index(op.f('ix_faces_photo_id'), 'faces', ['photo_id'], unique=False)
    op.create_index(op.f('ix_faces_studio_id'), 'faces', ['studio_id'], unique=False)
    op.create_table('guest_faces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('guest_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_session_id'], ['guest_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_faces_event_id'), 'guest_faces', ['event_id'], unique=False)
    op.create_index(op.f('ix_guest_faces_guest_session_id'), 'guest_faces', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_guest_faces_studio_id'), 'guest_faces', ['studio_id'], unique=False)
    op.create_table('guest_matches',
    sa.Column('guest_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('photo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_session_id'], ['guest_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guest_session_id', 'photo_id')
    )
    op.create_index(op.f('ix_guest_matches_event_id'), 'guest_matches', ['event_id'], unique=False)
    op.create_index('ix_guest_matches_session_created', 'guest_matches', ['guest_session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_guest_matches_studio_id'), 'guest_matches', ['studio_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('studio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('photo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', name='uq_jobs_photo')
    )
    op.create_index('ix_jobs_claimable', 'processing_jobs', ['event_id', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index(op.f('ix_processing_jobs_event_id'), 'processing_jobs', ['event_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_studio_id'), 'processing_jobs', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_studio_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_event_id'), table_name='processing_jobs')
    op.drop_index('ix_jobs_claimable', table_name='processing_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_guest_matches_studio_id'), table_name='guest_matches')
    op.drop_index('ix_guest_matches_session_created', table_name='guest_matches')
    op.drop_index(op.f('ix_guest_matches_event_id'), table_name='guest_matches')
    op.drop_table('guest_matches')
    op.drop_index(op.f('ix_guest_faces_studio_id'), table_name='guest_faces')
    op.drop_index(op.f('ix_guest_faces_guest_session_id'), table_name='guest_faces')
    op.drop_index(op.f('ix_guest_faces_event_id'), table_name='guest_faces')
    op.drop_table('guest_faces')
    op.drop_index(op.f('ix_faces_studio_id'), table_name='faces')
    op.drop_index(op.f('ix_faces_photo_id'), table_name='faces')
    op.drop_index(op.f('ix_faces_event_id'), table_name='faces')
    op.drop_table('faces')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_photos_uploaded_by'), table_name='photos')
    op.drop_index(op.f('ix_photos_studio_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_status'), table_name='photos')
    op.drop_index(op.f('ix_photos_event_id'), table_name='photos')
    op.drop_index('ix_photos_event_created', table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_payments_studio_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_event_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_guest_sessions_token_hash'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_studio_id'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_event_id'), table_name='guest_sessions')
    op.drop_table('guest_sessions')
    op.drop_index(op.f('ix_audit_log_studio_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_studio_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_studio_id'), table_name='events')
    op.drop_index('ix_events_studio_created', table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_qr_token'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_webhook_events_external_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_studios_slug'), table_name='studios')
    op.drop_table('studios')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
