"""event last_job_claimed_at for fair queueing

Revision ID: c3b1ea08e3b4
Revises: 0002_rls
Create Date: 2026-08-29 14:57:50.724877+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  - needed when a migration has a Vector column
import sqlalchemy as sa
from alembic import op

revision: str = 'c3b1ea08e3b4'
down_revision: str | None = '0002_rls'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('last_job_claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_events_last_job_claimed_at'), 'events', ['last_job_claimed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_last_job_claimed_at'), table_name='events')
    op.drop_column('events', 'last_job_claimed_at')
    # ### end Alembic commands ###
